---
- hosts: web_servers
  become: true
  tasks:
    - name: Print OS info
      ansible.builtin.package:
        name: httpd
        state: present
    - name: service httpd
      service:
        name: httpd
        state: restarted    
        enabled: yes
